### ISSUE TITLE
Invalid argument(s): name can't be null

### ISSUE THREAD

**Issue by SergeBerwert** [marcguilera/dependencies_flutter.dart#1]
Hi
Try to get your package to work I have the following code:

```
class Application extends StatelessWidget  {
  @override
  Widget build(BuildContext context){
    SimpleAuthFlutter.init(context);

    return InjectorWidget.bind(       
      bindFunc: (binder) {
        binder
        ..bindSingleton<ApiClient>(ApiClient())
        ..bindLazySingleton<SearchBloc>((injector, params) => SearchBloc(injector.get<ApiClient>()));
      },
      child: BlocProvider<AuthenticationBloc>(
        bloc: AuthenticationBloc(),
        child: MaterialApp(
          title: 'FlairFindr',
          theme: ThemeData(
            primarySwatch: Colors.blue
          ),
          routes: {
            '/home': (BuildContext context) => SearchPage()
          },
          //home: DecisionPage()
          home: ContactListPage()
        )
      )
    );
  }
```

and I get the following exception: 

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════
The following ArgumentError was thrown building Application(dirty):
Invalid argument(s): name can't be null

When the exception was thrown, this was the stack:
#0      checkArgument (package:quiver/check.dart:45:5)
#1      _InjectorBuilderContainer.setName (file:///C:/Code/flutter/.pub-cache/hosted/pub.dartlang.org/dependencies-0.1.4/lib/src/builder/_injector_builder_container.dart:8:5)
#2      new Injector (file:///C:/Code/flutter/.pub-cache/hosted/pub.dartlang.org/dependencies-0.1.4/lib/src/injector/injector.dart:33:25)
#3      new InjectorWidget.bind (file:///C:/Code/flutter/.pub-cache/hosted/pub.dartlang.org/dependencies_flutter-0.1.5/lib/src/injector_widget.dart:44:19)
#4      Application.build (package:flair_findr_flutter/application.dart:19:27)
#5      StatelessElement.build (package:flutter/src/widgets/framework.dart:3774:28)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#12     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:909:16)
#13     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:880:5)
#14     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:826:17)
#15     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2266:19)
#16     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:825:13)
#17     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:712:7)
#18     runApp (package:flutter/src/widgets/binding.dart:756:7)
#19     main (package:flair_findr_flutter/main.dart:5:16)
#20     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
#21     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

any ideas?

**Comment by marcguilera** [comment]
Should be fixed in the latest version. Side note, I tend to pass the injector fully into my block so the signature doesn't need to change should it need more objects in the future.
